language: php

php:
	- 5.6
	- 7.0
	- 7.1
env:
	- DB=mysql

before_script:
	- composer install
	- php app/console doctrine:database:create
	- php app/console doctrine:schema:create
 
install: 
	- composer require --dev phpunit/phpunit:~5.0

script :
	- phpunit -c app

